"""empty message

Revision ID: 943691b782fa
Revises: 
Create Date: 2019-12-24 12:11:18.499880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943691b782fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
